apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:5.1
          ports:
            - containerPort: 4001
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "250m"   # Request 250 millicores (0.25 vCPU)
              memory: "256Mi"  # Request 256MB RAM
            limits:
              cpu: "500m"   # Limit to 500 millicores (0.5 vCPU)
              memory: "512Mi"  # Limit to 512MB RAM

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
