# Base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package files and install dependencies with Yarn
COPY package*.json ./
RUN yarn install

# Copy the rest of the application
COPY . .

# Expose the updated port
EXPOSE 5001 6001

# Command to start the application
CMD ["node", "server.js"]
